# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
version: '3'

services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.2
    hostname: wazuh-certs-generator
    volumes:
      - /src/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/:/certificates/
      - /src/wazuh-docker/single-node/config/certs.yml:/config/certs.yml
volumes:
  cert-volume:
